
DROP TABLE IF EXISTS organizations CASCADE;

CREATE TABLE organizations (
  id SERIAL PRIMARY KEY,
  user_id VARCHAR(150) NOT NULL,
  FOREIGN KEY(user_id) REFERENCES users(id),
  lighthouseLabs VARCHAR(255) NOT NULL,
  Google VARCHAR(255) NOT NULL,
  Facebook VARCHAR(255) NOT NULL,
  Apple VARCHAR(255) NOT NULL,
  Microsoft VARCHAR(255) NOT NULL,
  Github VARCHAR(255) NOT NULL,
  Linkedin VARCHAR(255) NOT NULL
);
